### ISSUE TITLE
API v3 status

### ISSUE THREAD

**Issue by dgant** [glacials/whatsinstandard#36]
Good morning!

I noticed today that the v3 API doesn't contain sets past Kaladesh.

If v3 is deprecated, that's totally fine. Moving to v4 is trivially easy (I'm doing it right now). But if v3 *is* deprecated, then it might be a better policy to have deprecated API calls return a 410 status. It's easier to implement fallback logic for the API being unavailable than to handle incorrect information.

Thank you again for providing this very helpful tool!

**Comment by glacials** [comment]
Hi Dan, thanks for the feedback! You make a very good point and I agree.

Unfortunately since we're hosted on GitHub pages I can't easily return any status code. Would a 404 suffice?

In the next API version I can change the body to include some basic info about deprecation status, and set the sets array to `null` to break a version.

I'll also add this to the list of reasons to migrate off GitHub pages, but for now the list is too small to be worth the complexity.

**Comment by dgant** [comment]
404 is great, as are all these suggestions. :+1:

**Comment by glacials** [comment]
Done! Thanks for bringing this up!
