### ISSUE TITLE
Use the API to populate the lists on the page.

### ISSUE THREAD

**Issue by forstermatth** [glacials/whatsinstandard#45]
Everything (just about) that is on the page is presented by the API.
It would be a lot easier to maintain the lists if they were described in a single location, like the API
that is already available.

With either; 
* a framework, https://gist.github.com/Restuta/cda69e50a853aa64912d, 
* or a smaller custom JS (yet less powerful) solution, we could remove the duplicate information and have the front page reflect the information already presented by the API.

It seems as though Vue might be a good candidate as, from the examples, seems like it would be the least intrusive. I'd be willing to do a POC to see it would work without a ton of change.

Thoughts?

**Comment by glacials** [comment]
Definitely agree! The biggest benefit would be that I wouldn't need to manually change anything at midnight on release day, assuming enter/exit dates are populated ahead of time. Would love to see a POC.

I'm not a heavy JS person and this is a small project, so being able to make code changes without a lot of dev ramp up time is what I'd say priority 1 is in choosing a framework if any.

**Comment by inuyasha82** [comment]
Hi guys, 

i tried to do some tests with vue to dynamically update the page, and at the moment it seems quite promising. 

You can check my branch: https://github.com/inuyasha82/whatsinstandard/tree/dynamicupdate_test 
At the moment it lists only elements in the json, wrapping them around the block container. More logic has to be added, but i think it could be  a good start. 

I think anyway that if the API  update is implemented, then it will be easy to localize the page (see #39  ) (and where available the blocks can be displayed in the translated version).

Let me know what do you think of my POC, if you want i can  spend  some time and trying to implement it.

**Comment by glacials** [comment]
I'm impressed with this! As a non-JS person my only concern was overcomplicating the codebase, but this feels much simpler than the live site. This feels like a good path forward to a proper PR.

I've added a working API v5 todo list as #52, feel free to add anything you encounter that the site would need from the API to maintain the same feature set that it has today.

**Comment by inuyasha82** [comment]
I've updated my the branch above with:

1. Restored the warning label when the block will be released soon
2. Restored the set images (for every block)
3. Restored the label for future blocks. 

Anyway i have several questions on how to proceed: 

- At the moment i created the app.js file in the root folder, but probably this is not the right place (i think that it can be moved on the js folder)? 
- I added  vue.js file in both bower.json and package.json. But anyway since it is redundant having the library installed twice, where do you prefer to keep the library dependency? 
- I think that one of the problem with the current json format, is that identify blocks is not possible, so i can't easily group the sets by block (like in the original page), What do you suggest for that point? (i think the easiest solution is to add a new field to the block, that will also keep applications using the Api running, or probably we need to do some small changes to the web page).
- I noticed that you group the welcome deck set into the parent set, again like in the question above without any reference to the parent set it will be not easy to make this grouping, in my opinion probably the best solution in this case (just to avoid overloading the json with information) is to show the welcome deck as an independent set (that i don't think anyway is incorrect).

Let me know what do you think.

**Comment by inuyasha82** [comment]
Hey @glacials  do you had a chance to have a look at my repository? If yes what do you think about the issues/question above? 
The code iis nearly done. I just need to know how to proceed on the 4 questions above.

**Comment by glacials** [comment]
Hey sorry, been very busy past couple of weeks! I've finally looked at your branch!

> At the moment i created the app.js file in the root folder, but probably this is not the right place (i think that it can be moved on the js folder)?

Yeah ideally `js` folder is the right place, but honestly this isn't a super huge deal either way for a v1.

> I added vue.js file in both bower.json and package.json. But anyway since it is redundant having the library installed twice, where do you prefer to keep the library dependency?

Not being a JS person I actually don't really know where the right place is. Whatever you feel is more right is fine by me. If you'd like you can do some research about which tool people think is better to use for this sort of dependency.

>I think that one of the problem with the current json format, is that identify blocks is not possible, so i can't easily group the sets by block (like in the original page), What do you suggest for that point? (i think the easiest solution is to add a new field to the block, that will also keep applications using the Api running, or probably we need to do some small changes to the web page).

Each set returned by the API has a `block` field, which the frontend should be able to use to construct the blocks. Is this not the case? I'm okay with some rough-looking frontend code for now if that's what it takes, then we can reevaluate our needs when we bump API versions.

If you think the API absolutely needs to change before the frontend can arrange the setlist into blocks, I welcome you to PR the API with the changes it needs. But I do consider the visual arrangement of sets into blocks 100% an absolute need before we can merge this.

> I noticed that you group the welcome deck set into the parent set, again like in the question above without any reference to the parent set it will be not easy to make this grouping, in my opinion probably the best solution in this case (just to avoid overloading the json with information) is to show the welcome deck as an independent set (that i don't think anyway is incorrect).

Yeah I'm okay with this behavior for our v1.

**Comment by inuyasha82** [comment]
Oh, my bad, i didn't see the block field in the json! So probably things will be easier. I will try it in the next days.  So i think it makes things easier for my last two issues, i will try it in the next few days, and keep you updated. 

For the file i think that i'll move it into the js folder, and then i'll see where to put the vue.js dependency.

Thank you!

**Comment by inuyasha82** [comment]
Ok i have some thought about how to group items by block.
Even with block field, i'm not sure it easy to do without some preprocessing (maybe i'm wrong, i'm new to vue.js). 
So there are 2 possible solutions: 
1. I can rearragne items from original json programmatically to be grouped by blocks, and then use them in the html file. 
2. Or we can rearrange item in the json (as you proposed), but in that case the new version potentially can break application that are using these api, next version of my application will use them :)  ) 

Obviously the drawbacks of the first solution is that it will be a little bit more complex, and involve more computation, but anyway i think that the size of the json is not likely to change in the future, so probably if we want to keep the current structure, this is the best option. 

The drawbacks for the second one is that if someone is already using the api, should change its code in order to get it working with the new version.

Anyway i try to implement solution 1, just to see how complex it is.

**Comment by inuyasha82** [comment]
Hi @glacials, i spent some time today (Iless than 30mins) and i managed to group items by block, with the current format. The code is still in draft, but i think it's a good start. In that way we don't need to change the json format. 

When you have time have a look at it and let me know what do you think. 

Basically i created an associative array ike:
array["blockname] = set1, set2, ..., setN
For each block in standard. 

If i'm not wrong, all the sets in a block will drop on  the same day, correct?

**Comment by glacials** [comment]
Cool, I can take a look later today or tomorrow. It is correct that all sets in a block drop simultaneously. And I agree that this method is better for now,  rearranging ~10 items is virtually nothing computationally.

**Comment by glacials** [comment]
@inuyasha82 Looks to be shaping up nicely :) Feel free to open a pull request when you're ready.

**Comment by inuyasha82** [comment]
Hey @glacials  I just uploaded my update bower_components folder in my repo! (since it changed nearly all the files in that folder, are you able to double check that it is ok?)

And i'm not sure what else is needed to update before opening the Pull request. Can you have a look at it and let me know what is missing? 

And another question, since now we are populating the standard items via api, it could be nice to do it also for the recently dropped set, but for that we will need obviously a new json file. Otherwise we still have to manually update the html for the dropped sets. What do you think?

**Comment by glacials** [comment]
Go ahead and open a pull request now, it will make it easier to review. For your last question, we can support this in API v5 which I can write today or tomorrow.

**Comment by inuyasha82** [comment]
Ok!

**Comment by inuyasha82** [comment]
I suppose that this issue can be closed after merge of PR #59 ?

**Comment by glacials** [comment]
Yep, thanks for the reminder!
