### ISSUE TITLE
[Discussion] Bower  Dependencies in github

### ISSUE THREAD

**Issue by inuyasha82** [glacials/whatsinstandard#53]
Hi @glacials, 

i noticed that the bower_components is in the git repository.  

So, i  was reading about it (since usually i never added dependencies into my project repos) if it is a good practice or not, and the answer basically is: it's up to you (i found this article https://addyosmani.com/blog/checking-in-front-end-dependencies/). 

So my question is if for the dependencies it could be a good idea to remove them from git. For the dependencies in theory we only need bower.json file to be checked in.

Obviously there are pros and cons for both case:
The pros are: 

- Fewer files to mantain
- Only relevant code in the repository 
- Repos are smaller
- Running npm install/update you always ensure that all dependencies are installed, so the developer doesn't need to remember to add everytime the bower_components folder.

The cons are:

- You need to run an extra step when you download  (npm install/update)
- If the server are down for some reason you can't run the project. 
- Same as if the developer decide to remove his/her package from bower! :) (it happened once)

Obviously the cons of the "keep dependencies out" approach are the pros of the "check them in" approach. 
Same for the pros. 

The project is not so big, so i think that going for no dependencies on the repo could be a good idea in my opinion. 

What do you think? 
Another question is: why only bower dependencies? And not node dependencies?

**Comment by forstermatth** [comment]
@inuyasha82 This might have something to do with the Github pages hosting, where Github needs all of the code for the page? Just a guess though.

**Comment by glacials** [comment]
Yeah @forstermatth is exactly right. We used to keep dependencies out of the repo because I agree with the philosophy -- we had a `master` branch with no vendored dependencies and the `gh-pages` branch with the vendored dependencies. This meant that after every merged pull request I'd have to
```sh
git checkout master
git pull
git checkout gh-pages
git merge master
bower install
git commit
git push
```
which was tedious and confusing because `master` and `gh-pages` were _almost_ identical but not quite. So we changed to in-repo for simplicity.

> why only bower dependencies? And not node dependencies?

idk, I don't really know the pros/cons of this and forget why I set it up this way. I'm still a JS novice so it probably wasn't for any amazing reason.

**Comment by forstermatth** [comment]
Yea, maintaining parallel branches is such a pain. I think the simplicity of just keeping the deployed bower dependencies in the branch is the best way to go.

There is no reason to keep node dependencies in the repo, because they are not required for the website to run, only the API tests depend on them at the moment.

@inuyasha82 I see your need with `Vue` and the package.json. I believe, to keep it consistent, the right way would be to use Vue inside the bower dependency list over the package dependency list. It's confusing right now because the two lists aren't really defined in their role and relation to the code.

An alternative to this would be to switch to something like webpack, and compile a deployable folder which is kept up to date with all vendor files in the `gh-pages` branch.

**Comment by inuyasha82** [comment]
Ok, this make sense. 

I was not sure why this was done. I didn't thought about that. Sorry! :(

So then i will upload the new dependencies on my fork. (Vue and moment)

I had a look to package.json, apparently the package there are only necessary for test purposes, so this could be a reason that why that the node_modules folder was not included in the repository. 

Anyway the webpack idea could be useful (or since we are using vue.js they have vueify that is doing basically the same, i think that it could be the next task as soon as i finish working on the dynamic loading of json content, that is nearly done btw!).

**Comment by forstermatth** [comment]
Awesome!
