### ISSUE TITLE
Consider adding codenames for unnamed sets

### ISSUE THREAD

**Issue by NilsEnevoldsen** [glacials/whatsinstandard#84]
The set after Ravnica Allegiance is codenamed “[_Milk_](http://markrosewater.tumblr.com/post/174888234208/where-can-we-find-a-list-of-all-of-the-upcoming)”.  This is not a great name, but it's arguably better than “…”. I suggest adding it to the website with quotation marks around it. I don't have an opinion on the API.

Related to #65.

**Comment by glacials** [comment]
Hmm, I could go either way. The codenames are a nice way for you and me and Wizards to talk about upcoming sets, but the average person trying to find out what's in Standard probably doesn't get any value out of them, and might even be confused if we put them in. If we used them, it would have to be stupidly clear that they're codenames while also not being visually complicated for me to be okay with them.

On the tech side, it would take some additional work to be able to display them since the website is powered by its own API, which doesn't know about the "..." sets -- the JavaScript just puts them there as filler if the current round of sets isn't at least 4 sets long. Because of this I think this is blocked by #65. I'll leave this open for now and think on it a bit.

**Comment by NilsEnevoldsen** [comment]
Yes, I concur with that. I believe the quotation marks and light gray font would make it clear, but I agree there's a risk of confusion. Mockup attached for reference.

<img width="461" alt="screen shot 2018-06-14 at 8 45 40 pm" src="https://user-images.githubusercontent.com/222743/41444916-0356d332-7014-11e8-8aaf-b7271641ca2c.png">

**Comment by silasary** [comment]
The fact that War of the Spark was not entered by the time RNA was released (and therefore there were no upcoming sets in the API) caused issues for my code that consumes the API.

For the sake of API consumers, I'm strongly pushing for this to be done (at least on the API side)

**Comment by glacials** [comment]
Thanks for the feedback @silasary. Can you explain a bit more about your code and why the absence of upcoming sets broke it? Want to get a full understanding here of what's at stake and why.

**Comment by glacials** [comment]
Interesting, thanks for explaining! I do want the API to allow unnamed sets, but I also urge you try to handle these weird cases gracefully. Even when we allow unnamed sets, there's no guarantee we'll know the exact release date before the previous set releases.

**Comment by silasary** [comment]
This can be closed.

**Comment by glacials** [comment]
Thanks!
