### ISSUE TITLE
Not working on mobile (iOS 11) / gh pages outdated

### ISSUE THREAD

**Issue by tooomm** [glacials/whatsinstandard#88]
I only get a spinning circle and the list of sets is not loaded.

Basically only the right part of the desktop version is displayed.

I'm using iPhone 5s with iOS 11.4.1

---

**Update:** The problem was due to me having bookmarked the gh pages url, not the `whatsinstandard.com` url. My motivation was to always have the right, most up to date and correctly working link in case your domain expires at one point or there are any other problems for example.

But on my desktop it's not working and has the same problem:
https://glacials.github.io/whatsinstandard/

Why are there two versions of your site?! @glacials :)
Shouldn't https://whatsinstandard.com only redirect to gh pages? And shouldn't gh pages point to master?
I think you can also setup everything (with ssl) from the github settings nowerdays!

**Comment by glacials** [comment]
We moved off of GitHub Pages so that we could have a build step, see #55. This means we can build all of the following:

1. Auto-updating Standard sets when a set releases
2. Providing an API for the exact set of sets in Standard, no additional sets
3. Having one source of truth for set information

On GitHub Pages we could choose only two of these three.

I suggest you use `whatsinstandard.com`. I will stop the broken GitHub Pages builds so this is less confusing.

**Comment by tooomm** [comment]
>I will stop the broken GitHub Pages builds so this is less confusing.

It's still running... (a different version now though 😆 )

<br>

>On GitHub Pages we could choose only two of these three.

Could you elaborate further?

**Comment by forstermatth** [comment]
@tooomm Here is a previous discussion about endpoints and some of the reasoning behind switching: https://github.com/glacials/whatsinstandard/issues/52

**Comment by glacials** [comment]
I've replaced the `gh-pages` branch with an `index.html` that forwards you to the correct URL, since it looks like even turning GitHub Pages off does not remove previous builds from the GitHub Pages URL.

However, I suggest in the future that you do not use unadvertised URLs for websites. I understand your concern about risking using a URL with a layer of indirection that might fail, but in this case you introduced yourself to a different risk, one where the layer of indirection served its purpose and let the website owner switch out stuff behind the scenes.

If you do decide to use URLs that work incidentally but not officially, note that you are doing so at your own risk, and remember to look there first when something fails for you but doesn't seem to be for anyone else.

To summarize the discussions on GitHub Pages we've had over the years:

1. It's generally great
2. It's nice that our website is powered by our own API
3. But to get the website to update automatically when a set releases, we need to over-include sets in the API so JavaScript can display the right sets even 1 second after a rotation happens
4. But if we over-include sets in the API we need to tell third-party API consumers who just want currently-Standard sets to filter those sets out with [extra code][1] when they would prefer not to (#78)
5. To solve both those concerns we would need two API endpoints, one that over-includes for us, and one that includes exactly-Standard sets for third party consumers
6. But that re-introduces the problem of needing a human to update things when a set releases, because we can't automatically change the exactly-Standard JSON file without something janky like a script running somewhere that commits and pushes to GitHub, which I've done on other projects and is not fun to maintain

[1]: https://github.com/glacials/whatsinstandard/blob/901b47cadc6ed0f018624a226def5af12f53b769/api/README.md
